/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllRefineries: typeof import('./components/all-refineries/AllRefineries.vue')['default']
    AllRefineriesMap: typeof import('./components/all-refineries/AllRefineriesMap.vue')['default']
    AllRefineriesTable: typeof import('./components/all-refineries/AllRefineriesTable.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BasicChart: typeof import('./components/elements/BasicChart.vue')['default']
    BasicChartBar: typeof import('./components/elements/BasicChartBar.vue')['default']
    BasicEChart: typeof import('./components/elements/BasicEChart.vue')['default']
    BasicEChartWrapper: typeof import('./components/elements/BasicEChartWrapper.vue')['default']
    BasicLink: typeof import('./components/elements/BasicLink.vue')['default']
    BasicSource: typeof import('./components/russia/BasicSource.vue')['default']
    DataTableFiltersRow: typeof import('./components/data-table/DataTableFiltersRow.vue')['default']
    GoogleMap: typeof import('./components/google/GoogleMap.vue')['default']
    GoogleMapLoader: typeof import('./components/google/GoogleMapLoader.vue')['default']
    GoogleMapMarker: typeof import('./components/google/GoogleMapMarker.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OilProuctionByKommersant: typeof import('./components/OilProuctionByKommersant.vue')['default']
    OwnersList: typeof import('./components/all-refineries/OwnersList.vue')['default']
    RefineriesByVolume: typeof import('./components/russia/RefineriesByVolume.vue')['default']
    RosneftLocations: typeof import('./components/rosneft/RosneftLocations.vue')['default']
    RosneftLocationsCombined: typeof import('./components/rosneft/RosneftLocationsCombined.vue')['default']
    RosneftLocationsEn: typeof import('./components/rosneft/RosneftLocationsEn.vue')['default']
    RosneftLocationsRu: typeof import('./components/rosneft/RosneftLocationsRu.vue')['default']
    RosneftRefineries: typeof import('./components/rosneft/RosneftRefineries.vue')['default']
    RosneftSourcesRefineries: typeof import('./components/rosneft/RosneftSourcesRefineries.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
