/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/elaborations/ElaborationsPage': RouteRecordInfo<'/elaborations/ElaborationsPage', '/elaborations/ElaborationsPage', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/rosneft/RosneftLocationsPage': RouteRecordInfo<'/rosneft/RosneftLocationsPage', '/rosneft/RosneftLocationsPage', Record<never, never>, Record<never, never>>,
    '/rosneft/RosneftMapPage': RouteRecordInfo<'/rosneft/RosneftMapPage', '/rosneft/RosneftMapPage', Record<never, never>, Record<never, never>>,
    '/rosneft/RosneftPage': RouteRecordInfo<'/rosneft/RosneftPage', '/rosneft/RosneftPage', Record<never, never>, Record<never, never>>,
    '/rosneft/RosneftRefineriesPage': RouteRecordInfo<'/rosneft/RosneftRefineriesPage', '/rosneft/RosneftRefineriesPage', Record<never, never>, Record<never, never>>,
    '/rosneft/sources/': RouteRecordInfo<'/rosneft/sources/', '/rosneft/sources', Record<never, never>, Record<never, never>>,
    '/StatisticsPage': RouteRecordInfo<'/StatisticsPage', '/StatisticsPage', Record<never, never>, Record<never, never>>,
  }
}
